blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.blog, name='blog'),
    path('about/', views.about, name='blog'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('orders.urls')),
    path('', include('products.urls', namespace='products')),

] \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views


app_name = 'products'
urlpatterns = [
    path('catalog/', views.catalog, name='catalog'),
    path('category/<category_slug>/', views.catalog, name='product_list_by_category'),
    path('category/<category_slug>/<int:product_id>/<product_slug>/', views.product, name='product'),
]

products/models.py
from django.db import models
from django.urls import reverse


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, db_index=True, unique=True, blank=False, null=True, default=None, verbose_name='Категория')
    slug = models.SlugField(max_length=64, db_index=True, unique=True, blank=False, null=True, default=None, verbose_name='Транслит')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        verbose_name = "Категория товара"
        verbose_name_plural = "Категория товаров"

    def get_absolute_url(self):
        return reverse('products:product_list_by_category', args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=64, blank=False, null=True, default=None, db_index=True)
    slug = models.SlugField(max_length=64, blank=False, null=True, default=None, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.IntegerField(default=0)
    price_with_discount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, blank=False, null=True, default=None)
    short_description = models.TextField(blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "{}, {}".format(self.price, self.name)


    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def save(self, *args, **kwargs):

        if self.discount != 0 :
            price_with_discount = self.price * (100 - self.discount) / 100
        else:
            price_with_discount = 0

        self.price_with_discount = price_with_discount
        super(Product, self).save(*args, **kwargs)  # Call the "real" save() method.






class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images/')
    is_main = models.BooleanField(default = False)
    is_active = models.BooleanField(default = True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "{}".format(self.id)

    class Meta:
        verbose_name = "Фотография"
        verbose_name_plural = "Фотографии"



class Comment(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.product)

products/forms.py
from django import forms
from .models import *

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
#

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import *

def product(request, product_id, product_slug, category_slug):
    product = get_object_or_404(Product, id=product_id, slug=product_slug, is_active=True)

    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    print("     Session_key:   " + request.session.session_key)

    #Предложение похожих продуктов под основной инфой про продукт
    product_sug = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active = True).filter(product__category__slug=category_slug).exclude(product__id=product_id)
    product_suggestions = product_sug.order_by("-id")[:4]

    return render(request, 'products/product.html', {
        'product': product,
        'product_suggestions': product_suggestions,
    })


def catalog(request, category_slug=None):
    category = None
    categories = ProductCategory.objects.all()
    products = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active = True)
    if category_slug:
        category = get_object_or_404(ProductCategory, slug=category_slug)
        products = products.filter(product__category=category)
    return render(request, 'catalog_page/catalog.html', {
        'category': category,
        'categories': categories,
        'products': products,
    })

templates/products/product.html
{% extends 'base.html'%}
{% load static %}


{% block content %}
  <div class="container">
    <div class="product-main-----without-css">
      <div class="product-about-----without-css">

        <div class=""> <!-- название продукта -->
          <div class="">
            <h1 class="text">
              {{ product.name }}
            </h1>
          </div>
          <div class="">
            <h5 class="text-right">
              Код товара (ID):  {{ product.id }}
            </h5>
          </div>
        </div>


        <div> <!-- слайдер продукта : все о товаре описание и тд -->
          <div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
              <li role="presentation" class="active">
                <a href="#about_product" aria-controls="about_product" role="tab" data-toggle="tab">
                  Все о товаре
                </a>
              </li>
              <li role="presentation">
                <a href="#description" aria-controls="description" role="tab" data-toggle="tab">
                  Характеристики
                </a>
              </li>
              <li role="presentation">
                <a href="#products_comments" aria-controls="products_comments" role="tab" data-toggle="tab">
                  Отзывы
                </a>
              </li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content product-description-tabs">
              <div role="tabpanel" class="tab-pane active" id="about_product">
                <div class="row">

                  <div class="col-lg-6 col-md-6 col-sm-12">
                    {% if product.productimage_set.all|length_is:"1" %}
                      {% for image_item in product.productimage_set.all %}
                        <div class="slider__item">
                          <div class="product-image-item">
                            <img src="{{ image_item.image.url }}" class="img-responsive" />
                          </div>
                        </div>
                      {% endfor %}
                    {% else %}
                      <div class="slider">
                        <div class="slider__wrapper">
                          <div class="slider__items">
                              {% for image_item in product.productimage_set.all %}
                                <div class="slider__item">
                                  <div class="product-image-item">
                                    <img src="{{ image_item.image.url }}" class="img-responsive" />
                                  </div>
                                </div>
                              {% endfor %}
                          </div>
                        </div>
                        <a class="slider__control slider__control_prev" href="#" role="button"></a>
                        <a class="slider__control slider__control_next" href="#" role="button"></a>
                      </div>

                    {% endif %}
                  </div>




                  <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="row">
                      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        {% if product.discount != 0 %}
                          <div>
                            <div>
                              <h5>
                                <del>{{ product.price }}</del>
                                <span class="tile__price-currency"> ₴ </span>
                              </h5>
                            </div>

                            <div>
                              <h4>Price: {{ product.price_with_discount}} UAH</h4>
                            </div>
                          </div>
                        {% else %}
                          <div>
                            <div class="invisible">
                              <p>Empty space</p>
                            </div>

                            <div>
                              <h4>Price: {{ product.price}} UAH</h4>
                            </div>
                          </div>
                        {% endif %}
                      </div>

                      <div class="col-lg-6 col-md-6 col-sm-6">
                        <form class="form-inline" id="form_buying_product" action="{% url 'basket_adding' %}">
                          {% csrf_token %}

                          <div class="form-group">
                            <div class="input-number">
                              <div class="button input-number__minus" onclick="this.nextElementSibling.stepDown()">-</div>
                              <input class="input-number__input" type="number" min="1" max="69" value="1" id="number" readonly class="input-nmb-st">
                              <div class="button input-number__plus" onclick="this.previousElementSibling.stepUp()">+</div>
                            </div>
                          </div>
                          <div class="form-group">
                            {% if product.discount != 0 %}
                              <button type="submit" id="submit_btn" class="btn btn-success btn-buy"
                                data-product_id = "{{ product.id }}"
                                data-name = "{{ product.name }}"
                                data-price= "{{ product.price_with_discount}}"
                              >
                                Купить
                              </button>
                            {% else %}
                              <button type="submit" id="submit_btn" class="btn btn-success btn-buy"
                                data-product_id = "{{ product.id }}"
                                data-name = "{{ product.name }}"
                                data-price= "{{ product.price }}"
                              >
                                Купить
                              </button>
                            {% endif %}
                          </div>


                        </form>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="panel panel-default">
                          <div class="panel-heading"><b>Способы оплаты</b></div>
                          <div class="panel-body">
                            <ul>
                              <li>банковская карта (Visa/Mastercard)</li>
                              <li>наличный/безналичный расчет курьеру при получении товара</li>
                              <li>безналичная оплата с расчетного счета организации</li>
                            </ul>
                          </div>
                        </div>

                        <div class="panel panel-default">
                          <div class="panel-heading"><b>Стоимость доставки</b></div>
                          <div class="panel-body">
                            <ul>
                              <li>Киев и Киевская область - 50грн</li>
                              <li>БЕСПЛАТНАЯ ДОСТАВКА при заказе на 800 грн</li>
                              <li>Забрать из пункта выдачи самостоятельно</li>
                              <li>Другие регионы - необходимо уточнить у нашего менеджера</li>
                              <li>Из Новой Почты - по тарифам перевозчика</li>
                              <li>Курьер Новая почта - по тарифам перевозчика </li>
                            </ul>
                          </div>
                        </div>

                        <div class="panel panel-default">
                          <div class="panel-heading"><b>Гарантия, Качество</b></div>
                          <div class="panel-body">
                            <ul>
                              <li>Мы гарантируем соответствие товара.</li>
                              <li>Обмен/возврат товара надлежащего качества без лишних вопросов в течении 14 дней</li>
                              <li>Официальная гарантия от производителей</li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>

                  </div>


                </div>
              </div>
              <div role="tabpanel" class="tab-pane" id="description">
                <h3>тут должно быть окно с описанием товара, его основных характеристик</h3>
                {{ product.description }}
              </div>
              <div role="tabpanel" class="tab-pane" id="products_comments">
                <h3>тут должно быть окно с отзывами</h3>
              </div>
            </div>

          </div>

        </div>


        <div class="row">
          <div class="col-lg-12">
            <h3>Описание товара:</h3>
            {{ product.description }}
            </p>
          </div>
        </div>

      </div>

    </div>

  </div>

  <div class="row">
    <div class="col-lg-12">
      <h1 class="text-center">
        Также вас может заинтересовать
      </h1>
      <div>
        {% for product_image  in product_suggestions  %}
          <div class="col-lg-3 col-md-4 col-sm-6">
            {% include 'blog/product_item.html' %}
          </div>
        {% endfor %}
      </div>
    </div>
  </div>


{% endblock %}