blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.blog, name='blog'),
    path('about/', views.about, name='blog'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('orders.urls')),
    path('', include('products.urls', namespace='products')),

] \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views


app_name = 'products'
urlpatterns = [
    path('catalog/', views.catalog, name='catalog'),
    path('category/<category_slug>/', views.catalog, name='product_list_by_category'),
    path('category/<category_slug>/<int:product_id>/<product_slug>/', views.product, name='product'),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Subscriber(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=128)

    def __str__(self):
        return "{} {}".format(email, name)

    class Meta:
        verbose_name = "MySubcriber"
        verbose_name_plural = "A lot of Subscribers"

blog/forms.py
from django import forms
from .models import *

class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        fields = ["name", "email"]

blog/views.py
from django.shortcuts import render
from .forms import SubscriberForm
from products.models import *

def blog(request):
    form = SubscriberForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        print(form.cleaned_data)
        data = form.cleaned_data
        print(data["name"])
        new_form = form.save()

    # if a GET (or any other method) we'll create a blank form
    else:
        form = SubscriberForm()

    return render(request, 'blog/base.html', {'form': form})



def home(request):
    all_products = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active = True)
    category_kofe_v_zernah = all_products.filter(product__category__id=1)
    category_kofe_v_kapsulah = all_products.filter(product__category__id=2)

    all_products_last_add = all_products.order_by("-id")[:4]
    category_kofe_v_zernah_last_add = category_kofe_v_zernah.order_by("-id")[:4]
    category_kofe_v_kapsulah_last_add = category_kofe_v_kapsulah.order_by("-id")[:4]

    return render(request, 'blog/home.html', {
        'all_products' : all_products,
        'all_products_last_add' : all_products_last_add,
        'category_kofe_v_zernah_last_add' : category_kofe_v_zernah_last_add,
        'category_kofe_v_kapsulah_last_add' : category_kofe_v_kapsulah_last_add,
    })


def about(request):
    return render(request, 'blog/about.html', {})

templates/blog/about.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
  <div class="container-fluid">

    <div class="row">
      <div class="">
        <h1 class="text-center">О создателе</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <img src="{% static 'images/about-me.png'%}" class="img-responsive" />
      </div>

      <div class="col-lg-6">
        <p>Зовут Артем. 23 года. Закончил магистратуру КПИ, факультет Радиотехники, технарь.</p>


        <ul>
          <b>Личные качества:</b>
          <li>Упорный</li>
          <li>Целенаправленный</li>
          <li>Ответственный</li>
          <li>Люблю улучшать/оптимизировать что-либо</li>
        </ul>

        <ul>
          <b>Интересы:</b>
          <li>Интересуют компьютерные и технические новшества</li>
          <li>Велосипедные прогулки</li>
          <li>Здоровый образ жизни</li>
          <li>Саморазвитие</li>
        </ul>

        <ul>
          <b>Ожидания:</b>
          <li>Работать в молодой команде</li>
          <li>Усовершенствовать hard / soft skills</li>
          <li>Профессиональный рост</li>
          <li>Получить опыт в перспективной компании</li>
          <li>Работать над интересными проектами</li>
          <li>Достойная заработная плата</li>
        </ul>


      </div>

    </div>

    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h3 class="text-center">
          <b><i>Есть желание расти и развиваться в программировании, стать full-stack разработчиком(для начала). Потому что достойная заработная плата, а также есть идеи программ, которые хочу воплотить в жизнь и для которых нужно больше коммерческого опыта программирования. <br>Также хочу познакомиться с новыми интересными людьми, профессионалами своего дела.</i></b>
        </h3>
        <p class="text-center">Мой <a href="https://t.me/GooDviNon">Telegram</a></p>
      </div>
    </div>


  </div>

{% endblock %}

templates/blog/home.html
{% extends 'base.html'%}
{% load static %}


{% block content %}
<!-- <div class="section-top">  -->
<!--   <img src="{% static 'images/kofe-zerna-dymok-meshok.jpg' %}" class="img-responsive" />  -->
<!-- </div>  -->
<div class="section-top">
  <img src="{% static 'images/coffee_home_page.jpg'%}" class="img-responsive" />
</div>
<div class="section section1">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="text-center">
        Новые поступления
      </h1>
      <h3 class="text-center">Всего на сайте представлено {{all_products|length }} товаров</h3>
    </div>
    <div>
      {% for product_image  in all_products_last_add %}
        <div class="col-lg-3 col-md-4 col-sm-6">
          {% include 'blog/product_item.html' %}
        </div>
      {% endfor %}
    </div>
  </div>
</div>




<div class="section section-delivery">
  <div>
    <img src="{% static 'images/free-shipping.png'%}" class="free-shipping-image" />
  </div>
  <div>
    <h1>Free delivery</h1>
    <h1>for orders over 800 UAH</h1>
  </div>
</div>

<div class="section section2">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="text-center">
        Кофе в зернах (последние обновления в разделе)
      </h1>
    </div>
    <div>
      {% for product_image  in category_kofe_v_zernah_last_add  %}
        <div class="col-lg-3 col-md-4 col-sm-6">
          {% include 'blog/product_item.html' %}
        </div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="section section3">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="text-center">
        Кофе в капсулах (последние обновления в разделе)
      </h1>
    </div>
    <div>
      {% for product_image in category_kofe_v_kapsulah_last_add  %}
        <div class="col-lg-3 col-md-4 col-sm-6">
          {% include 'blog/product_item.html' %}
        </div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="section section4">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="text-center">
        Новые поступления
      </h1>
      <h3 class="text-center">Всего на сайте представлено {{all_products|length }} товаров</h3>
    </div>

    <div>
      {% for product_image  in all_products_last_add %}
        <div class="col-lg-3 col-md-4 col-sm-6">
          {% include 'blog/product_item.html' %}
        </div>
      {% endfor %}
    </div>
  </div>
</div>


{% endblock %}

templates/blog/landing.html
{% extends 'base.html'%}
{% load static %}

{% block content %}

<div>
  <div>
    <a href="/">
      <img src="static/images/main_logo.png" alt="main_logo" width="65">
    </a>

    <div class="nav_catalog" href="#">
      <svg class="catalog" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 00-.5.5v9a.5.5 0 00.5.5h13a.5.5 0 00.5-.5v-9a.5.5 0 00-.5-.5zm-13-1A1.5 1.5 0 000 3.5v9A1.5 1.5 0 001.5 14h13a1.5 1.5 0 001.5-1.5v-9A1.5 1.5 0 0014.5 2h-13z" clip-rule="evenodd"/>
        <path fill-rule="evenodd" d="M5 8a.5.5 0 01.5-.5h7a.5.5 0 010 1h-7A.5.5 0 015 8zm0-2.5a.5.5 0 01.5-.5h7a.5.5 0 010 1h-7a.5.5 0 01-.5-.5zm0 5a.5.5 0 01.5-.5h7a.5.5 0 010 1h-7a.5.5 0 01-.5-.5z" clip-rule="evenodd"/>
        <circle cx="3.5" cy="5.5" r=".5"/>
        <circle cx="3.5" cy="8" r=".5"/>
        <circle cx="3.5" cy="10.5" r=".5"/>
      </svg>
      <span class="text">&#8194;Каталог</span>
      <div class="nav_catalog_content">
        <ul>
          <li><a href="#home">Что нибудь 1</a></li>
          <li><a href="#home">Что нибудь 2</a></li>
          <li><a href="#home">Что нибудь 3</a></li>
          <li><a href="#home">Что нибудь 4</a></li>
          <li><a href="#home">Что нибудь 5</a></li>
          <li><a href="#home">Что нибудь 6</a></li>
          <li><a href="#home">Что нибудь 7</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="peaces_of_nav">
    <button class="basket">
      <a href="#">
        <svg class="basket" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M4.646 8.146a.5.5 0 01.708 0L8 10.793l2.646-2.647a.5.5 0 01.708.708l-3 3a.5.5 0 01-.708 0l-3-3a.5.5 0 010-.708z" clip-rule="evenodd"/>
          <path fill-rule="evenodd" d="M8 1a.5.5 0 01.5.5v9a.5.5 0 01-1 0v-9A.5.5 0 018 1z" clip-rule="evenodd"/>
          <path fill-rule="evenodd" d="M1.5 13.5A1.5 1.5 0 003 15h10a1.5 1.5 0 001.5-1.5v-8A1.5 1.5 0 0013 4h-1.5a.5.5 0 000 1H13a.5.5 0 01.5.5v8a.5.5 0 01-.5.5H3a.5.5 0 01-.5-.5v-8A.5.5 0 013 5h1.5a.5.5 0 000-1H3a1.5 1.5 0 00-1.5 1.5v8z" clip-rule="evenodd"/>
        </svg>
        <span class="text">&#8194;Корзина</span>
      </a>
    </button>
    <button class="login">
      <a href="#">
        <svg class="login" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 100-6 3 3 0 000 6zm7 1.5a.5.5 0 01.5-.5h2a.5.5 0 010 1h-2a.5.5 0 01-.5-.5zm-2-3a.5.5 0 01.5-.5h4a.5.5 0 010 1h-4a.5.5 0 01-.5-.5zm0-3a.5.5 0 01.5-.5h4a.5.5 0 010 1h-4a.5.5 0 01-.5-.5zm2 9a.5.5 0 01.5-.5h2a.5.5 0 010 1h-2a.5.5 0 01-.5-.5z" clip-rule="evenodd"/>
        </svg>
        <span class="text">&#8194;Войти</span>
      </a>
    </button>
  </div>
</div>

<section class="catalog_of_products">
  <div class="catalog_of_products_box">
    <h2>catalog of products</h2>
    <ul>
      <li><a href="#home">Что нибудь 1</a></li>
      <li><a href="#home">Что нибудь 2</a></li>
      <li><a href="#home">Что нибудь 3</a></li>
      <li><a href="#home">Что нибудь 4</a></li>
      <li><a href="#home">Что нибудь 5</a></li>
      <li><a href="#home">Что нибудь 6</a></li>
      <li><a href="#home">Что нибудь 7</a></li>
    </ul>
  </div>
</section>

<section class="window_with_products">
  <h2> Товары </h2>

  <div>
    <form action="" method="post"> {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button type="submit">Submit</button>
      </div>
    </form>
  </div>



  <div class="products_box">
    <div class="products">
      <button class = "btn btn-success">Ура, я подключил Bootstrap!</button>
    </div>
  </div>
</section>

{% endblock %}

templates/blog/product_item.html
<div class="product-item">
  <div class="product-item-space">
    <div class="product_img">
      <a href="{% url 'products:product' product_image.product.category.slug product_image.product.id product_image.product.slug %}">
        <img src="{{ product_image.image.url }}" class="product-item-img"/>
      </a>
      <!-- {{ c.get_absolute_url }} -->
    </div>

    {% if product_image.product.discount %}
      <div>
        <span class="discount-container"> - {{ product_image.product.discount }} % </span>
      </div>
    {% endif %}

    <div>
      <h4> {{ product_image.product.name }}</h4>
      <p>
        {{ product_image.product.description|truncatechars_html:60 }}
      </p>
    </div>


    <div class="add-to-cart-btn">
      {% if product_image.product.discount != 0 %}
        <div class="">
          <div class="">
            <h5>
              <del>{{ product_image.product.price }}</del>
              <span class="tile__price-currency"> ₴ </span>
            </h5>
          </div>

          <div class="">
            <h4>
              {{ product_image.product.price_with_discount}}
              <span class=""> ₴ </span>
            </h4>
          </div>
        </div>
      {% else %}
        <div class="">
          <div class="invisible">
            <p>Empty space</p>
          </div>

          <div class="">
            <h4>
              {{ product_image.product.price}}
              <span class=""> ₴ </span>
            </h4>
          </div>
        </div>
      {% endif %}

      <button class="btn btn-success">
        Добавить в корзину
      </button>
    </div>


  </div>
</div>