blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.blog, name='blog'),
    path('about/', views.about, name='blog'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('orders.urls')),
    path('', include('products.urls', namespace='products')),

] \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views


app_name = 'products'
urlpatterns = [
    path('catalog/', views.catalog, name='catalog'),
    path('category/<category_slug>/', views.catalog, name='product_list_by_category'),
    path('category/<category_slug>/<int:product_id>/<product_slug>/', views.product, name='product'),
]

templates/catalog_page/catalog.html
{% extends 'base.html'%}
{% load static %}

{% block content %}

  <div class="row">
    <div class="col-lg-12">
      <h2 class="text-center">
        {% if category %}
          {{ category.name }}
        {% else %}
          Все товары представленые на сайте
        {% endif %}
      </h2>
    </div>
  </div>


  <div class="row">
    <div class="col-lg-3 col-md-4 col-sm-6">
      <div class="list-group list-group-catalog">
        <a class="list-group-item active text-center">
          Категории товаров:
        </a>
        <a href="{% url "products:catalog" %}" class="list-group-item {% if not category %}selected{% endif %}">Все продукты
          <!--<span class="badge">{{categ_all|length}}</span>-->
        </a>
        {% for c in categories %}
          <a href="{{ c.get_absolute_url }}" class="list-group-item {% if category.slug == c.slug %}class="selected"{% endif %}">{{ c.name }}
            <!--<span class="badge">{{ products|length}}</span>-->
          </a>
          <!--
          {% if c.slug == p.product.category.slug %}
            {{c|length}}
          {% endif %}
          {% for p in products %}
            {% if c.slug == p.product.category.slug %}
              {{category}}
            {% endif %}
          {% endfor %}
        -->

        {% endfor %}
      </div>

    </div>


    {% for product_image  in products %}
      <div class="col-lg-3 col-md-4 col-sm-6">
        {% include 'blog/product_item.html' %}
      </div>
    {% endfor %}


  </div>


  <!--
  {% include "catalog_page/pagination.html" with page=catalog_products %}
     -->

{% endblock %}

templates/catalog_page/detail.html
{% extends 'base.html'%}
{% load static %}

{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

templates/catalog_page/pagination.html
<div class="row">
  <div class="col-lg-12" align="center">
    <ul class="pagination">
      {% if post.has_previous %}
        <li class="arrow"><a href="/category/{{ category.slug }}?page={{ page }}{{ catalog_products.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><a href="">&laquo;</a></li>
      {% endif %}

      {% for pag in post.paginator.page_range %}
        {% if pag == post.number %}
          <li class="active"><a href="/category/{{ category.slug }}?page={{ page }}">{{ pag }}</a></li>
        {% else %}
          <li><a href="/category/{{ category.slug }}?page={{ pag }}">{{ pag }}</a></li>
        {% endif %}
      {% endfor %}

      {% if post.has_next %}
        <li class="arrow"><a href="/category/{{ category.slug }}?page={{ page }}{{ catalog_products.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><a href="">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>